//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace <#cs Write(Project.Namespace)#>.Client.Localisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class <#cs Write(Definition.Name)#>Loc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal <#cs Write(Definition.Name)#>Loc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("<#cs Write(Project.Namespace)#>.Client.Localisation.<#cs Write(Definition.Name)#>Loc", typeof(<#cs Write(Definition.Name)#>Loc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
<#cs
var entries = Entries.Select(e => e.Field).ToList();

if (!(Definition.IsArray || Definition.IsEnumeration))
{
  entries.Add("Create" + Definition.Name);
  entries.Add("Edit"  + Definition.Name);
  entries.Add(Definition.Name + "s");
}

foreach(var entry in entries.OrderBy(e => e))
{
	WriteLine("        /// <summary>");
	WriteLine($"        ///   Looks up a localized string similar to {entry}:.");
	WriteLine("        /// </summary>");
	WriteLine($"        public static string {entry} {{");
	WriteLine("            get {");
	WriteLine($"                return ResourceManager.GetString(\"{entry}\", resourceCulture);");
	WriteLine("            }");
	WriteLine("        }");
	WriteLine("        ");
}

Result = Result.TrimEnd();
#>
    }
}
<#cs SetOutputPath(false)#>