//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Todo.Client.Localisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FilterOperatorLoc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FilterOperatorLoc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Todo.Client.Localisation.FilterOperatorLoc", typeof(FilterOperatorLoc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        public static string OperatorContains {
            get {
                return ResourceManager.GetString("OperatorContains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not contain.
        /// </summary>
        public static string OperatorDoesNotContain {
            get {
                return ResourceManager.GetString("OperatorDoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends with.
        /// </summary>
        public static string OperatorEndsWith {
            get {
                return ResourceManager.GetString("OperatorEndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equals.
        /// </summary>
        public static string OperatorEquals {
            get {
                return ResourceManager.GetString("OperatorEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater than.
        /// </summary>
        public static string OperatorGreaterThan {
            get {
                return ResourceManager.GetString("OperatorGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater than or equal.
        /// </summary>
        public static string OperatorGreaterThanOrEqual {
            get {
                return ResourceManager.GetString("OperatorGreaterThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is empty.
        /// </summary>
        public static string OperatorIsEmpty {
            get {
                return ResourceManager.GetString("OperatorIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not empty.
        /// </summary>
        public static string OperatorIsNotEmpty {
            get {
                return ResourceManager.GetString("OperatorIsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than.
        /// </summary>
        public static string OperatorLessThan {
            get {
                return ResourceManager.GetString("OperatorLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than or equal.
        /// </summary>
        public static string OperatorLessThanOrEqual {
            get {
                return ResourceManager.GetString("OperatorLessThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not equals.
        /// </summary>
        public static string OperatorNotEquals {
            get {
                return ResourceManager.GetString("OperatorNotEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts with.
        /// </summary>
        public static string OperatorStartsWith {
            get {
                return ResourceManager.GetString("OperatorStartsWith", resourceCulture);
            }
        }
    }
}
