//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace <# Project.Namespace#>.Client.Localisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FilterLoc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FilterLoc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("<# Project.Namespace#>.Client.Localisation.FilterLoc", typeof(FilterLoc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Filter Conditions.
        /// </summary>
        public static string ActiveConditions {
            get {
                return ResourceManager.GetString("ActiveConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Condition.
        /// </summary>
        public static string AddCondition {
            get {
                return ResourceManager.GetString("AddCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add at least one filter condition before saving..
        /// </summary>
        public static string AddConditionBeforeSaving {
            get {
                return ResourceManager.GetString("AddConditionBeforeSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add at least one filter condition before setting a default..
        /// </summary>
        public static string AddConditionBeforeSettingDefault {
            get {
                return ResourceManager.GetString("AddConditionBeforeSettingDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear all filters.
        /// </summary>
        public static string ClearAllFilters {
            get {
                return ResourceManager.GetString("ClearAllFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Default.
        /// </summary>
        public static string ClearDefault {
            get {
                return ResourceManager.GetString("ClearDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a filter name before saving..
        /// </summary>
        public static string EnterNameBeforeSaving {
            get {
                return ResourceManager.GetString("EnterNameBeforeSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name for filter....
        /// </summary>
        public static string FilterNamePlaceholder {
            get {
                return ResourceManager.GetString("FilterNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove condition.
        /// </summary>
        public static string RemoveCondition {
            get {
                return ResourceManager.GetString("RemoveCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved filters.
        /// </summary>
        public static string SavedFilters {
            get {
                return ResourceManager.GetString("SavedFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select field....
        /// </summary>
        public static string SelectField {
            get {
                return ResourceManager.GetString("SelectField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a filter....
        /// </summary>
        public static string SelectFilter {
            get {
                return ResourceManager.GetString("SelectFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as Default.
        /// </summary>
        public static string SetAsDefault {
            get {
                return ResourceManager.GetString("SetAsDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value....
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
    }
}
<#cs SetOutputPathAndSkipOtherDefinitions(); Encoding = new System.Text.UTF8Encoding(true);#>